import Symptom from './models/symptom';
import Disease from './models/disease';
import SideEffect from './models/sideEffect';

//LIST OF ALL MEDICAL SYMPTOMS KNOWN

export const SYMPTOMS = [
    new Symptom(1, "N/A"),
    new Symptom(2, "Cachexia"),
    new Symptom(3, "Chills"),
    new Symptom(4, "Convulsions"),
    new Symptom(5, "Deformity"),
    new Symptom(6, "Discharge"),
    new Symptom(7, "Dizziness"),
    new Symptom(8, "Fatigue"),
    new Symptom(9, "Hypothermia"),
    new Symptom(10, "Jaundice"),
    new Symptom(11, "Muscle Weakness"),
    new Symptom(12, "Pyrexia"),
    new Symptom(13, "Sweats"),
    new Symptom(14, "Swelling"),
    new Symptom(15, "Swollen or Painful Lymph Node(s)"),
    new Symptom(16, "Weight Gain"),
    new Symptom(17, "Arrhythmia"),
    new Symptom(18, "Bradycardia"),
    new Symptom(19, "Chest Pain"),
    new Symptom(20, "Claudication"),
    new Symptom(21, "Palpitations"),
    new Symptom(22, "Tachycardia"),
    new Symptom(23, "Dry Mouth"),
    new Symptom(24, "Epistaxis"),
    new Symptom(25, "Halitosis"),
    new Symptom(26, "Hearing Loss"),
    new Symptom(27, "Nasal Discharge"),
    new Symptom(28, "Otalgia"),
    new Symptom(29, "Otorrhea"),
    new Symptom(30, "Sore Throat"),
    new Symptom(31, "Toothache"),
    new Symptom(32, "Tinnitus"),
    new Symptom(33, "Trismus"),
    new Symptom(34, "Abdominal Pain"),
    new Symptom(35, "Bloating"),
    new Symptom(36, "Belching"),
    new Symptom(37, "Bleeding"),
    new Symptom(38, "Constipation"),
    new Symptom(39, "Diarrhea"),
    new Symptom(40, "Dysphagia"),
    new Symptom(41, "Dyspepsia"),
    new Symptom(42, "Fecal Incontinence"),
    new Symptom(43, "Flatulence"),
    new Symptom(44, "Nausea"),
    new Symptom(45, "Odynophagia"),
    new Symptom(46, "Proctalgia Fugax"),
    new Symptom(47, "Pyrosis"),
    new Symptom(48, "Rectal Tenesmus"),
    new Symptom(49, "Steatorrhea"),
    new Symptom(50, "Vomiting"),
    new Symptom(51, "Alopecia"),
    new Symptom(52, "Hirsutism"),
    new Symptom(53, "Hypertrichosis"),
    new Symptom(54, "Abrasion"),
    new Symptom(55, "Anasarca"),
    new Symptom(56, "Brusing"),
    new Symptom(57, "Blister"),
    new Symptom(58, "Edema"),
    new Symptom(59, "Itching"),
    new Symptom(60, "Laceration"),
    new Symptom(61, "Rash"),
    new Symptom(62, "Urticaria"),
    new Symptom(63, "Abnormal Posturing"),
    new Symptom(64, "Acalculia"),
    new Symptom(65, "Agnosia"),
    new Symptom(66, "Alexia"),
    new Symptom(67, "Amnesia"),
    new Symptom(68, "Anomia"),
    new Symptom(69, "Anosognosia"),
    new Symptom(70, "Apraxia"),
    new Symptom(71, "Ataxia"),
    new Symptom(72, "Cataplexy"),
    new Symptom(73, "Confusion"),
    new Symptom(74, "Dysarthria"),
    new Symptom(75, "Dysdiadochokinesia"),
    new Symptom(76, "Dysgraphia"),
    new Symptom(77, "Hallucination"),
    new Symptom(78, "Headache"),
    new Symptom(79, "Muscle Cramps"),
    new Symptom(80, "Tremor"),
    new Symptom(81, "Insomnia"),
    new Symptom(82, "Loss Of Consciousness"),
    new Symptom(83, "Neck Stiffness"),
    new Symptom(84, "Opisthotonus"),
    new Symptom(85, "Paralysis"),
    new Symptom(86, "Paresthesia"),
    new Symptom(87, "Prosopagnosia"),
    new Symptom(88, "Somnolence"),
    new Symptom(89, "Abnormal Vaginal Bleeding"),
    new Symptom(90, "Amenorrhea"),
    new Symptom(91, "Infertility"),
    new Symptom(92, "Painful Intercourse"),
    new Symptom(93, "Pelvic Pain"),
    new Symptom(94, "Vaginal Discharge"),
    new Symptom(95, "Blurred Vision"),
    new Symptom(96, "Double Vision"),
    new Symptom(97, "Exophthalmos"),
    new Symptom(98, "Nystagmus"),
    new Symptom(99, "Amusia"),
    new Symptom(100, "Anhedonia"),
    new Symptom(101, "Anxiety"),
    new Symptom(102, "Apathy"),
    new Symptom(103, "Confabulation"),
    new Symptom(104, "Depression"),
    new Symptom(105, "Aelusion"),
    new Symptom(106, "Euphoria"),
    new Symptom(107, "Homicidal Ideation"),
    new Symptom(108, "Irritability"),
    new Symptom(109, "Mania"),
    new Symptom(110, "Paranoid Ideation"),
    new Symptom(111, "Phobia"),
    new Symptom(112, "Suicidal Ideation"),
    new Symptom(113, "Apnea"),
    new Symptom(114, "Cough"),
    new Symptom(115, "Dyspnea"),
    new Symptom(116, "Hemoptysis"),
    new Symptom(117, "Pleuritic Chest Pain"),
    new Symptom(118, "Arthralgia"),
    new Symptom(119, "Back Pain"),
    new Symptom(120, "Sciatica"),
    new Symptom(121, "Dysuria"),
    new Symptom(122, "Hematospermia"),
    new Symptom(123, "Hematuria"),
    new Symptom(124, "Impotence"),
    new Symptom(125, "Polyuria"),
    new Symptom(126, "Strangury"),
    new Symptom(127, "Urethral Discharge"),
    new Symptom(128, "Urinary Frequency"),
    new Symptom(129, "Urinary Incontinence "),
    new Symptom(130, "Urinary Retention")
];

export const DISEASE = [
    new Disease(1, "N/A"),
    new Disease(2, "Anthrax"),
    new Disease(3, "Arboviral Diseases"),
    new Disease(4, "Babesiosis"),
    new Disease(5, "Botulism"),
    new Disease(6, "Brucellosis"),
    new Disease(7, "Campylobacteriosis"),
    new Disease(8, "Candida Auris"),
    new Disease(9, "Carbapenem-Resistant Enterobacteriaceae"),
    new Disease(10, "Chancroid"),
    new Disease(11, "Chlamydia Trachomatis"),
    new Disease(12, "Cholera"),
    new Disease(13, "Coccidioidomycosis"),
    new Disease(14, "Congenital syphilis"),
    new Disease(15, "Cryptosporidiosis"),
    new Disease(16, "Cyclosporiasis"),
    new Disease(17, "Dengue Virus Infections"),
    new Disease(18, "Diphtheria"),
    new Disease(19, "Ehrlichiosis and Anaplasmosis"),
    new Disease(20, "Giardiasis"),
    new Disease(21, "Gonorrhea"),
    new Disease(22, "Haemophilus Influenzae"),
    new Disease(23, "Hansen's Disease"),
    new Disease(24, "Hantavirus"),
    new Disease(25, "Hemolytic Uremic Syndrome"),
    new Disease(26, "Hepatitis A"),
    new Disease(27, "Hepatitis B"),
    new Disease(28, "Hepatitis C"),
    new Disease(29, "HIV"),
    new Disease(30, "Influenza"),
    new Disease(31, "Invasive Pneumococcal Disease"),
    new Disease(32, "Legionellosis"),
    new Disease(33, "Leptospirosis"),
    new Disease(34, "Cancer"),
    new Disease(35, "Carbon Monoxide Poisoning"),
    new Disease(36, "Silicosis"),
    new Disease(37, "Listeriosis"),
    new Disease(38, "Lyme Disease"),
    new Disease(39, "Malaria"),
    new Disease(40, "Measles"),
    new Disease(41, "Meningococcal Disease"),
    new Disease(42, "Mumps"),
    new Disease(43, "Novel Influenza A"),
    new Disease(44, "Pertussis"),
    new Disease(45, "Plague"),
    new Disease(46, "Poliomyelitis"),
    new Disease(47, "Poliovirus Infection"),
    new Disease(48, "Psittacosis"),
    new Disease(49, "Q Fever"),
    new Disease(50, "Rabies"),
    new Disease(51, "Rubella"),
    new Disease(52, "Salmonella Paratyphi"),
    new Disease(53, "Salmonella Typhi"),
    new Disease(54, "Salmonellosis"),
    new Disease(55, "Shiga Toxin-Producing Escherichia Coli"),
    new Disease(56, "Shigellosis"),
    new Disease(57, "Smallpox"),
    new Disease(58, "Spotted Fever Rickettsiosis"),
    new Disease(59, "Streptococcal Toxic Shock Syndrome"),
    new Disease(60, "Syphilis"),
    new Disease(61, "Tetanus"),
    new Disease(62, "Trichinellosis"),
    new Disease(63, "Tuberculosis"),
    new Disease(64, "Tularemia"),
    new Disease(65, "Varicella"),
    new Disease(66, "Vibriosis"),
    new Disease(67, "Viral Hemorrhagic Fever"),
    new Disease(68, "Yellow Fever"),
    new Disease(69, "Zika Virus")
];

export const SIDEEFFECT = [
    new SideEffect(1, "N/A"),
    new SideEffect(2, "Cachexia"),
    new SideEffect(3, "Chills"),
    new SideEffect(4, "Convulsions"),
    new SideEffect(5, "Deformity"),
    new SideEffect(6, "Discharge"),
    new SideEffect(7, "Dizziness"),
    new SideEffect(8, "Fatigue"),
    new SideEffect(9, "Hypothermia"),
    new SideEffect(10, "Jaundice"),
    new SideEffect(11, "Muscle Weakness"),
    new SideEffect(12, "Pyrexia"),
    new SideEffect(13, "Sweats"),
    new SideEffect(14, "Swelling"),
    new SideEffect(15, "Swollen or Painful Lymph Node(s)"),
    new SideEffect(16, "Weight Gain"),
    new SideEffect(17, "Arrhythmia"),
    new SideEffect(18, "Bradycardia"),
    new SideEffect(19, "Chest Pain"),
    new SideEffect(20, "Claudication"),
    new SideEffect(21, "Palpitations"),
    new SideEffect(22, "Tachycardia"),
    new SideEffect(23, "Dry Mouth"),
    new SideEffect(24, "Epistaxis"),
    new SideEffect(25, "Halitosis"),
    new SideEffect(26, "Hearing Loss"),
    new SideEffect(27, "Nasal Discharge"),
    new SideEffect(28, "Otalgia"),
    new SideEffect(29, "Otorrhea"),
    new SideEffect(30, "Sore Throat"),
    new SideEffect(31, "Toothache"),
    new SideEffect(32, "Tinnitus"),
    new SideEffect(33, "Trismus"),
    new SideEffect(34, "Abdominal Pain"),
    new SideEffect(35, "Bloating"),
    new SideEffect(36, "Belching"),
    new SideEffect(37, "Bleeding"),
    new SideEffect(38, "Constipation"),
    new SideEffect(39, "Diarrhea"),
    new SideEffect(40, "Dysphagia"),
    new SideEffect(41, "Dyspepsia"),
    new SideEffect(42, "Fecal Incontinence"),
    new SideEffect(43, "Flatulence"),
    new SideEffect(44, "Nausea"),
    new SideEffect(45, "Odynophagia"),
    new SideEffect(46, "Proctalgia Fugax"),
    new SideEffect(47, "Pyrosis"),
    new SideEffect(48, "Rectal Tenesmus"),
    new SideEffect(49, "Steatorrhea"),
    new SideEffect(50, "Vomiting"),
    new SideEffect(51, "Alopecia"),
    new SideEffect(52, "Hirsutism"),
    new SideEffect(53, "Hypertrichosis"),
    new SideEffect(54, "Abrasion"),
    new SideEffect(55, "Anasarca"),
    new SideEffect(56, "Brusing"),
    new SideEffect(57, "Blister"),
    new SideEffect(58, "Edema"),
    new SideEffect(59, "Itching"),
    new SideEffect(60, "Laceration"),
    new SideEffect(61, "Rash"),
    new SideEffect(62, "Urticaria"),
    new SideEffect(63, "Abnormal Posturing"),
    new SideEffect(64, "Acalculia"),
    new SideEffect(65, "Agnosia"),
    new SideEffect(66, "Alexia"),
    new SideEffect(67, "Amnesia"),
    new SideEffect(68, "Anomia"),
    new SideEffect(69, "Anosognosia"),
    new SideEffect(70, "Apraxia"),
    new SideEffect(71, "Ataxia"),
    new SideEffect(72, "Cataplexy"),
    new SideEffect(73, "Confusion"),
    new SideEffect(74, "Dysarthria"),
    new SideEffect(75, "Dysdiadochokinesia"),
    new SideEffect(76, "Dysgraphia"),
    new SideEffect(77, "Hallucination"),
    new SideEffect(78, "Headache"),
    new SideEffect(79, "Muscle Cramps"),
    new SideEffect(80, "Tremor"),
    new SideEffect(81, "Insomnia"),
    new SideEffect(82, "Loss Of Consciousness"),
    new SideEffect(83, "Neck Stiffness"),
    new SideEffect(84, "Opisthotonus"),
    new SideEffect(85, "Paralysis"),
    new SideEffect(86, "Paresthesia"),
    new SideEffect(87, "Prosopagnosia"),
    new SideEffect(88, "Somnolence"),
    new SideEffect(89, "Abnormal Vaginal Bleeding"),
    new SideEffect(90, "Amenorrhea"),
    new SideEffect(91, "Infertility"),
    new SideEffect(92, "Painful Intercourse"),
    new SideEffect(93, "Pelvic Pain"),
    new SideEffect(94, "Vaginal Discharge"),
    new SideEffect(95, "Blurred Vision"),
    new SideEffect(96, "Double Vision"),
    new SideEffect(97, "Exophthalmos"),
    new SideEffect(98, "Nystagmus"),
    new SideEffect(99, "Amusia"),
    new SideEffect(100, "Anhedonia"),
    new SideEffect(101, "Anxiety"),
    new SideEffect(102, "Apathy"),
    new SideEffect(103, "Confabulation"),
    new SideEffect(104, "Depression"),
    new SideEffect(105, "Aelusion"),
    new SideEffect(106, "Euphoria"),
    new SideEffect(107, "Homicidal Ideation"),
    new SideEffect(108, "Irritability"),
    new SideEffect(109, "Mania"),
    new SideEffect(110, "Paranoid Ideation"),
    new SideEffect(111, "Phobia"),
    new SideEffect(112, "Suicidal Ideation"),
    new SideEffect(113, "Apnea"),
    new SideEffect(114, "Cough"),
    new SideEffect(115, "Dyspnea"),
    new SideEffect(116, "Hemoptysis"),
    new SideEffect(117, "Pleuritic Chest Pain"),
    new SideEffect(118, "Arthralgia"),
    new SideEffect(119, "Back Pain"),
    new SideEffect(120, "Sciatica"),
    new SideEffect(121, "Dysuria"),
    new SideEffect(122, "Hematospermia"),
    new SideEffect(123, "Hematuria"),
    new SideEffect(124, "Impotence"),
    new SideEffect(125, "Polyuria"),
    new SideEffect(126, "Strangury"),
    new SideEffect(127, "Urethral Discharge"),
    new SideEffect(128, "Urinary Frequency"),
    new SideEffect(129, "Urinary Incontinence "),
    new SideEffect(130, "Urinary Retention")
];