import Symptom from './models/symptom';
import Disease from './models/disease';

//LIST OF ALL MEDICAL SYMPTOMS KNOWN

export const SYMPTOMS = [
    new Symptom(1, "N/A"),
    new Symptom(2, "Cachexia"),
    new Symptom(3, "Chills"),
    new Symptom(4, "Convulsions"),
    new Symptom(5, "Deformity"),
    new Symptom(6, "Discharge"),
    new Symptom(7, "Dizziness"),
    new Symptom(8, "Fatigue"),
    new Symptom(9, "Hypothermia"),
    new Symptom(10, "Jaundice"),
    new Symptom(11, "Muscle Weakness"),
    new Symptom(12, "Pyrexia"),
    new Symptom(13, "Sweats"),
    new Symptom(14, "Swelling"),
    new Symptom(15, "Swollen or Painful Lymph Node(s)"),
    new Symptom(16, "Weight Gain"),
    new Symptom(17, "Arrhythmia"),
    new Symptom(18, "Bradycardia"),
    new Symptom(19, "Chest Pain"),
    new Symptom(20, "Claudication"),
    new Symptom(21, "Palpitations"),
    new Symptom(22, "Tachycardia"),
    new Symptom(23, "Dry Mouth"),
    new Symptom(24, "Epistaxis"),
    new Symptom(25, "Halitosis"),
    new Symptom(26, "Hearing Loss"),
    new Symptom(27, "Nasal Discharge"),
    new Symptom(28, "Otalgia"),
    new Symptom(29, "Otorrhea"),
    new Symptom(30, "Sore Throat"),
    new Symptom(31, "Toothache"),
    new Symptom(32, "Tinnitus"),
    new Symptom(33, "Trismus"),
    new Symptom(34, "Abdominal Pain"),
    new Symptom(35, "Bloating"),
    new Symptom(36, "Belching"),
    new Symptom(37, "Bleeding"),
    new Symptom(38, "Constipation"),
    new Symptom(39, "Diarrhea"),
    new Symptom(40, "Dysphagia"),
    new Symptom(41, "Dyspepsia"),
    new Symptom(42, "Fecal Incontinence"),
    new Symptom(43, "Flatulence"),
    new Symptom(44, "Nausea"),
    new Symptom(45, "Odynophagia"),
    new Symptom(46, "Proctalgia Fugax"),
    new Symptom(47, "Pyrosis"),
    new Symptom(48, "Rectal Tenesmus"),
    new Symptom(49, "Steatorrhea"),
    new Symptom(50, "Vomiting"),
    new Symptom(51, "Alopecia"),
    new Symptom(52, "Hirsutism"),
    new Symptom(53, "Hypertrichosis"),
    new Symptom(54, "Abrasion"),
    new Symptom(55, "Anasarca"),
    new Symptom(56, "Brusing"),
    new Symptom(57, "Blister"),
    new Symptom(58, "Edema"),
    new Symptom(59, "Itching"),
    new Symptom(60, "Laceration"),
    new Symptom(61, "Rash"),
    new Symptom(62, "Urticaria"),
    new Symptom(63, "Abnormal Posturing"),
    new Symptom(64, "Acalculia"),
    new Symptom(65, "Agnosia"),
    new Symptom(66, "Alexia"),
    new Symptom(67, "Amnesia"),
    new Symptom(68, "Anomia"),
    new Symptom(69, "Anosognosia"),
    new Symptom(70, "Apraxia"),
    new Symptom(71, "Ataxia"),
    new Symptom(72, "Cataplexy"),
    new Symptom(73, "Confusion"),
    new Symptom(74, "Dysarthria"),
    new Symptom(75, "Dysdiadochokinesia"),
    new Symptom(76, "Dysgraphia"),
    new Symptom(77, "Hallucination"),
    new Symptom(78, "Headache"),
    new Symptom(79, "Muscle Cramps"),
    new Symptom(80, "Tremor"),
    new Symptom(81, "Insomnia"),
    new Symptom(82, "Loss Of Consciousness"),
    new Symptom(83, "Neck Stiffness"),
    new Symptom(84, "Opisthotonus"),
    new Symptom(85, "Paralysis"),
    new Symptom(86, "Paresthesia"),
    new Symptom(87, "Prosopagnosia"),
    new Symptom(88, "Somnolence"),
    new Symptom(89, "Abnormal Vaginal Bleeding"),
    new Symptom(90, "Amenorrhea"),
    new Symptom(91, "Infertility"),
    new Symptom(92, "Painful Intercourse"),
    new Symptom(93, "Pelvic Pain"),
    new Symptom(94, "Vaginal Discharge"),
    new Symptom(95, "Blurred Vision"),
    new Symptom(96, "Double Vision"),
    new Symptom(97, "Exophthalmos"),
    new Symptom(98, "Nystagmus"),
    new Symptom(99, "Amusia"),
    new Symptom(100, "Anhedonia"),
    new Symptom(101, "Anxiety"),
    new Symptom(102, "Apathy"),
    new Symptom(103, "Confabulation"),
    new Symptom(104, "Depression"),
    new Symptom(105, "Aelusion"),
    new Symptom(106, "Euphoria"),
    new Symptom(107, "Homicidal Ideation"),
    new Symptom(108, "Irritability"),
    new Symptom(109, "Mania"),
    new Symptom(110, "Paranoid Ideation"),
    new Symptom(111, "Phobia"),
    new Symptom(112, "Suicidal Ideation"),
    new Symptom(113, "Apnea"),
    new Symptom(114, "Cough"),
    new Symptom(115, "Dyspnea"),
    new Symptom(116, "Hemoptysis"),
    new Symptom(117, "Pleuritic Chest Pain"),
    new Symptom(118, "Arthralgia"),
    new Symptom(119, "Back Pain"),
    new Symptom(120, "Sciatica"),
    new Symptom(121, "Dysuria"),
    new Symptom(122, "Hematospermia"),
    new Symptom(123, "Hematuria"),
    new Symptom(124, "Impotence"),
    new Symptom(125, "Polyuria"),
    new Symptom(126, "Strangury"),
    new Symptom(127, "Urethral Discharge"),
    new Symptom(128, "Urinary Frequency"),
    new Symptom(129, "Urinary Incontinence "),
    new Symptom(130, "Urinary Retention")
];

export const DISEASE = [
    new Disease(1, "N/A"),
    new Disease(2, "Anthrax"),
    new Disease(3, "Arboviral Diseases"),
    new Disease(4, "Babesiosis"),
    new Disease(5, "Botulism"),
    new Disease(6, "Brucellosis"),
    new Disease(7, "Campylobacteriosis"),
    new Disease(8, "Candida Auris"),
    new Disease(9, "Carbapenem-Resistant Enterobacteriaceae"),
    new Disease(10, "Chancroid"),
    new Disease(11, "Chlamydia Trachomatis"),
    new Disease(12, "Cholera"),
    new Disease(13, "Coccidioidomycosis"),
    new Disease(14, "Congenital syphilis"),
    new Disease(15, "Cryptosporidiosis"),
    new Disease(16, "Cyclosporiasis"),
    new Disease(17, "Dengue Virus Infections"),
    new Disease(18, "Diphtheria"),
    new Disease(19, "Ehrlichiosis and Anaplasmosis"),
    new Disease(20, "Giardiasis"),
    new Disease(21, "Gonorrhea"),
    new Disease(22, "Haemophilus Influenzae"),
    new Disease(23, "Hansen's Disease"),
    new Disease(24, "Hantavirus"),
    new Disease(25, "Hemolytic Uremic Syndrome"),
    new Disease(26, "Hepatitis A"),
    new Disease(27, "Hepatitis B"),
    new Disease(28, "Hepatitis C"),
    new Disease(29, "HIV"),
    new Disease(30, "Influenza"),
    new Disease(31, "Invasive Pneumococcal Disease"),
    new Disease(32, "Legionellosis"),
    new Disease(33, "Leptospirosis"),
    new Disease(34, "Cancer"),
    new Disease(35, "Carbon Monoxide Poisoning"),
    new Disease(36, "Silicosis"),
    new Disease(37, "Listeriosis"),
    new Disease(38, "Lyme Disease"),
    new Disease(39, "Malaria"),
    new Disease(40, "Measles"),
    new Disease(41, "Meningococcal Disease"),
    new Disease(42, "Mumps"),
    new Disease(43, "Novel Influenza A"),
    new Disease(44, "Pertussis"),
    new Disease(45, "Plague"),
    new Disease(46, "Poliomyelitis"),
    new Disease(47, "Poliovirus Infection"),
    new Disease(48, "Psittacosis"),
    new Disease(49, "Q Fever"),
    new Disease(50, "Rabies"),
    new Disease(51, "Rubella"),
    new Disease(52, "Salmonella Paratyphi"),
    new Disease(53, "Salmonella Typhi"),
    new Disease(54, "Salmonellosis"),
    new Disease(55, "Shiga Toxin-Producing Escherichia Coli"),
    new Disease(56, "Shigellosis"),
    new Disease(57, "Smallpox"),
    new Disease(58, "Spotted Fever Rickettsiosis"),
    new Disease(59, "Streptococcal Toxic Shock Syndrome"),
    new Disease(60, "Syphilis"),
    new Disease(61, "Tetanus"),
    new Disease(62, "Trichinellosis"),
    new Disease(63, "Tuberculosis"),
    new Disease(64, "Tularemia"),
    new Disease(65, "Varicella"),
    new Disease(66, "Vibriosis"),
    new Disease(67, "Viral Hemorrhagic Fever"),
    new Disease(68, "Yellow Fever"),
    new Disease(69, "Zika Virus")
];